import "@/styles/globals.css";
import type { Metadata } from "next";
import { JetBrains_Mono, Noto_Sans, Noto_Sans_TC } from "next/font/google";
import Nav from "./Nav";

//https://nextjs.org/docs/app/api-reference/components/font
//https://nextjs.org/docs/app/building-your-application/optimizing/fonts#google-fonts
const NotoSans = Noto_Sans({ subsets: ["latin"], variable: "--font-noto-sans" });
const NotoSansTC = Noto_Sans_TC({ subsets: [], variable: "--font-noto-sans-tc" });
const JetBrainsMono = JetBrains_Mono({ subsets: ["latin"], variable: "--font-jetbrains-mono" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-Hant">
      <body className={`flex h-dvh ${NotoSans.variable} ${NotoSansTC.variable} ${JetBrainsMono.variable}`}>
        <div className="basis-1/5 flex justify-end">
          <Nav />
        </div>
        <main className="basis-4/5 p-10">{children}</main>
      </body>
    </html>
  );
}
